
build:
    version: "3.0"
loans:
    message: "Welcome to this Application"
    contactPerson:
        name: "Kamal_Prod"
        email: abc@gmail.com
    contactInfo:
        - 9876568
        - 9879976